import { supabase } from './supabase';
import type { Invoice, InvoiceStatus, InvoiceType } from '../types/invoice';

export interface InvoiceFilters {
  type?: InvoiceType | 'all';
  status?: InvoiceStatus | 'all';
  search?: string;
  fromDate?: string;
  toDate?: string;
}

export async function listInvoices(filters: InvoiceFilters): Promise<Invoice[]> {
  let query = supabase
    .from('invoices')
    .select('*')
    .order('issued_at', { ascending: false })
    .order('created_at', { ascending: false });

  if (filters.type && filters.type !== 'all') {
    query = query.eq('type', filters.type);
  }
  if (filters.status && filters.status !== 'all') {
    query = query.eq('status', filters.status);
  }
  if (filters.fromDate) {
    query = query.gte('issued_at', filters.fromDate);
  }
  if (filters.toDate) {
    query = query.lte('issued_at', filters.toDate);
  }
  if (filters.search) {
    const term = filters.search.trim();
    if (term.length > 0) {
      query = query.or(
        `number.ilike.%${term}%,customer->>email.ilike.%${term}%,customer->>lastName.ilike.%${term}%,variable_symbol.ilike.%${term}%`,
      );
    }
  }

  const { data, error } = await query;
  if (error) throw error;
  return (data ?? []) as Invoice[];
}

export async function markInvoicePaid(id: string): Promise<Invoice> {
  const { data, error } = await supabase
    .from('invoices')
    .update({ status: 'paid', paid_at: new Date().toISOString() })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return data as Invoice;
}

export async function markInvoiceCancelled(id: string): Promise<Invoice> {
  const { data, error } = await supabase
    .from('invoices')
    .update({ status: 'cancelled', cancelled_at: new Date().toISOString() })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return data as Invoice;
}

export async function openInvoiceView(invoice: Invoice): Promise<void> {
  // Open the invoice as a real PDF generated by Vercel serverless function.
  // Function validates HMAC token and renders HTML→PDF on demand. Admin needs
  // the same token; we fetch it via service-side RPC (admin already has
  // permission via RLS to read invoice id, but invoice_view_token is service-role
  // only). Easier path: admin calls a wrapper RPC that returns token if caller
  // is admin. For simplicity now, admin just navigates to /api/faktura/{id}?t={token}
  // by computing token via Supabase RPC `get_admin_invoice_token`.
  const { data: token, error } = await supabase.rpc('get_admin_invoice_token', {
    p_id: invoice.id,
  });
  if (error || !token) {
    throw error ?? new Error('Nepodařilo se získat token pro zobrazení faktury.');
  }
  const url = `/api/faktura/${invoice.id}?t=${token}`;
  window.open(url, '_blank', 'noopener,noreferrer');
}
